**Step1: Import Packages**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2: Create a dataframe using list**

In [4]:
names=['Ramesh','Suresh','Satish']
#pd.DataFrame(data,index,columns)
pd.DataFrame(names)

0
0  Ramesh
1  Suresh
2  Satish

**Step-3 : Changing of index**

In [9]:
names=['Ramesh','Suresh','Satish']
index=['A','B','C']
pd.DataFrame(names,index)

0
A  Ramesh
B  Suresh
C  Satish

**Step-4: Add the columns**

In [8]:
names=['Ramesh','Suresh','Satish']
index=['A','B','C']
cols=['Names']
pd.DataFrame(names,index,cols)

Names
A  Ramesh
B  Suresh
C  Satish

**Step-5: Data and Columns**

In [10]:
names=['Ramesh','Suresh','Satish']
index=['A','B','C']
cols=['Names']
pd.DataFrame(names,columns=cols)

Names
0  Ramesh
1  Suresh
2  Satish

In [11]:
pd.DataFrame(['Ramesh','Suresh','Satish'],['A','B','C'],['Names'])

Names
A  Ramesh
B  Suresh
C  Satish

**Step-6: Multiple Columns**

In [5]:
names=['Ramesh','Suresh','Satish']
age=[22,23,24]                                     # use the zip 
cols=['Names','Age']
df=pd.DataFrame(zip(names,age),columns=cols)
df

Names  Age
0  Ramesh   22
1  Suresh   23
2  Satish   24

**Step-7: Add a new column to a existed dataframe**

-  In above first we have taken data

-  then created a dataframe

-  now we want to add a new data based on requirement.

In [7]:
city=['RCB','CSK','MI']
df['City']=city
df

Names  Age City
0  Ramesh   22  RCB
1  Suresh   23  CSK
2  Satish   24   MI

In [20]:
marks=[97,98,96]
df['Marks']=marks
df

Names  Age City  Marks
0  Ramesh   22  RCB     97
1  Suresh   23  CSK     98
2  Satish   24   MI     96

**Step-8: Update the column with new values**

In [9]:
df['Marks']=[96,97,98]
df

Names  Age City  Marks
0  Ramesh   22  RCB     96
1  Suresh   23  CSK     97
2  Satish   24   MI     98

**Step-9: Create empty dataframe and add the columns**

In [27]:
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [28]:
df1['Names']=['Rahul','Suman','Rohan','Santosh']
df1['City']=['BDK','RKL','BDK','BBSR']
df1['Age']=[24,26,22,29]
df1

Names  City  Age
0    Rahul   BDK   24
1    Suman   RKL   26
2    Rohan   BDK   22
3  Santosh  BBSR   29

**Step-10: Create a Dataframe using Dictionary**

In [30]:
d={'Names':['Rahul','Suman','Rohan','Santosh'],
    'City':['BDK','RKL','BDK','BBSR'],
    'Age':[24,26,22,29]}
d

{'Names': ['Rahul', 'Suman', 'Rohan', 'Santosh'],
 'City': ['BDK', 'RKL', 'BDK', 'BBSR'],
 'Age': [24, 26, 22, 29]}

In [31]:
pd.DataFrame(d)

Names  City  Age
0    Rahul   BDK   24
1    Suman   RKL   26
2    Rohan   BDK   22
3  Santosh  BBSR   29

In [39]:
e={'Names':['Rahul'],
    'City':['BDK'],
    'Age':[24]}
e

{'Names': ['Rahul'], 'City': ['BDK'], 'Age': [24]}

In [41]:
pd.DataFrame(e,index=[0])

Names City  Age
0  Rahul  BDK   24

**Step-11: Saving the DataFrame**

In [42]:
df.to_csv('data.csv')

In [45]:
df.to_excel('data.xlsx')

**step:12- How to read the DataFrame ?** 

In [3]:
pd.read_csv('data.csv')

Unnamed: 0   Names  Age City  Marks
0           0  Ramesh   22  RCB     96
1           1  Suresh   23  CSK     97
2           2  Satish   24   MI     98

In [10]:
df

Names  Age City  Marks
0  Ramesh   22  RCB     96
1  Suresh   23  CSK     97
2  Satish   24   MI     98

In [11]:
pd.read_excel('data.xlsx')

Unnamed: 0   Names  Age City  Marks
0           0  Ramesh   22  RCB     96
1           1  Suresh   23  CSK     97
2           2  Satish   24   MI     98

In [39]:
d={'Names':['Rahul','Suman','Rohan','Santosh'],
    'City':['BDK','RKL','BDK','BBSR'],
    'Age':[24,26,22,29]}
df2=pd.DataFrame(d)
df2

Names  City  Age
0    Rahul   BDK   24
1    Suman   RKL   26
2    Rohan   BDK   22
3  Santosh  BBSR   29

In [24]:
df2.to_csv('data1.csv',index=False)

In [25]:
pd.read_csv('data1.csv')

Names  City  Age Gender
0    Rahul   BDK   24   Male
1    Suman   RKL   26   Male
2    Rohan   BDK   22   Male
3  Santosh  BBSR   29   Male

In [26]:
df2.to_excel('data1.xlsx',index=False)


In [27]:
pd.read_excel('data1.xlsx')

Names  City  Age Gender
0    Rahul   BDK   24   Male
1    Suman   RKL   26   Male
2    Rohan   BDK   22   Male
3  Santosh  BBSR   29   Male

In [43]:
df2['Gender']=['Male','Male','Male','Male']
df2

Names  City  Age Gender
0    Rahul   BDK   24   Male
1    Suman   RKL   26   Male
2    Rohan   BDK   22   Male
3  Santosh  BBSR   29   Male

**Step-13 : How to drop the column ?**

**Index**

In [28]:
df2.drop(index=3)

Names City  Age Gender
0  Rahul  BDK   24   Male
1  Suman  RKL   26   Male
2  Rohan  BDK   22   Male

In [29]:
df2

Names  City  Age Gender
0    Rahul   BDK   24   Male
1    Suman   RKL   26   Male
2    Rohan   BDK   22   Male
3  Santosh  BBSR   29   Male

**Columns**

In [33]:
df2.drop(columns ='Gender')

Names  City
0    Rahul   BDK
1    Suman   RKL
2    Rohan   BDK
3  Santosh  BBSR

In [44]:
df2.drop(columns =['Gender','Age'])

Names  City
0    Rahul   BDK
1    Suman   RKL
2    Rohan   BDK
3  Santosh  BBSR

In [45]:
df2

Names  City  Age Gender
0    Rahul   BDK   24   Male
1    Suman   RKL   26   Male
2    Rohan   BDK   22   Male
3  Santosh  BBSR   29   Male

**Label         ,    Axis**

In [46]:
df2.drop('Marks')

KeyError: "['Marks'] not found in axis"

In [49]:
df2.drop('Gender',axis=1)

Names  City  Age
0    Rahul   BDK   24
1    Suman   RKL   26
2    Rohan   BDK   22
3  Santosh  BBSR   29

In [50]:
df2

Names  City  Age Gender
0    Rahul   BDK   24   Male
1    Suman   RKL   26   Male
2    Rohan   BDK   22   Male
3  Santosh  BBSR   29   Male

**Inplace**

-  When we do the operation the result output is not overwritting.

-  the original dataframe is same as it is.

-  in order to do this we need to use **inplace**.

-  by default inplace = False.

-  make inplace = True if you want to overwrite the result.

In [51]:
df2.drop('Gender',axis=1,inplace=True)

In [52]:
df2

Names  City  Age
0    Rahul   BDK   24
1    Suman   RKL   26
2    Rohan   BDK   22
3  Santosh  BBSR   29

**Step:14- Rename the column**

In [56]:
Dict={'City':'city'}
df2.rename(Dict,axis=1,inplace=True)

In [57]:
df2

Names  city  Age
0    Rahul   BDK   24
1    Suman   RKL   26
2    Rohan   BDK   22
3  Santosh  BBSR   29

In [58]:
Dict={2:'A'}
df2.rename(Dict,axis=0,inplace=True)

In [59]:
df2

Names  city  Age
0    Rahul   BDK   24
1    Suman   RKL   26
A    Rohan   BDK   22
3  Santosh  BBSR   29

In [65]:
x=list(range(1,11))
arx=np.array(x)
ary=np.square(arx)
arz=np.array(arx*arx*arx)
arx,ary,arz

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100]),
 array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000]))

In [72]:
data=zip(arx,ary,arz)
Columns=['X','Y','Z']
df3=pd.DataFrame(data,columns=Columns)
df3

X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

**Important Methods**

In [93]:
len(df3)

10

In [74]:
df3.shape

(10, 3)

In [78]:
df3.size

30

In [94]:
df3.head()

X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125

In [95]:
df3.head(1)

X  Y  Z
0  1  1  1

In [96]:
df3.tail()

X    Y     Z
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [92]:
df3.tail(1)

X    Y     Z
9  10  100  1000

In [85]:
df3.isnull()

X      Y      Z
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [86]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Z       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes


In [98]:
df3.dtypes
# if any categorical columns occurs
# it represnt as object

X    int64
Y    int64
Z    int64
dtype: object

**Step-15 : Select a column**

In [100]:
df3.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [106]:
df3['X']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64

In [105]:
df3[['X','Y']]

X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [108]:
type(df3['X'])                              # one dimension - Series

pandas.core.series.Series

In [110]:
type(df3[['X','Y']])                       # more the one dimension - DataFrames

pandas.core.frame.DataFrame

In [111]:
df3['X'].shape

(10,)

In [112]:
df3[['X','Y']].shape

(10, 2)

In [115]:
df3['X'].values                                 # extracting the data 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
df3['Y'].values

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [116]:
df3[['Y','Z']].values

array([[   1,    1],
       [   4,    8],
       [   9,   27],
       [  16,   64],
       [  25,  125],
       [  36,  216],
       [  49,  343],
       [  64,  512],
       [  81,  729],
       [ 100, 1000]])

In [118]:
df3['Y'].values.tolist()                  # giving the outout in list format

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [120]:
a=df3['X'].values.tolist()
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]